# Generated by Django 5.0.1 on 2024-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('phrase', models.CharField(max_length=200)),
                ('dark_pattern_type', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
            ],
        ),
    ]
