# Generated by Django 5.0.1 on 2024-02-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
    ]
