# Generated by Django 5.0.1 on 2024-02-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_server', '0002_detectionresult_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='phrase',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='site_url',
            field=models.URLField(max_length=400),
        ),
    ]
